// <auto-generated />
using DataAcessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAcessLayer.Migrations
{
    [DbContext(typeof(FOODContext))]
    [Migration("20260327192102_ading_madplan_table")]
    partial class ading_madplan_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("DataAcessLayer.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("DataAcessLayer.Models.Madplan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FredagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LørdagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MandagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OnsdagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SøndagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TisdagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TorsdagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Uge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("år")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FredagId");

                    b.HasIndex("LørdagId");

                    b.HasIndex("MandagId");

                    b.HasIndex("OnsdagId");

                    b.HasIndex("SøndagId");

                    b.HasIndex("TisdagId");

                    b.HasIndex("TorsdagId");

                    b.ToTable("Madplans");
                });

            modelBuilder.Entity("DataAcessLayer.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("KitchenType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Servings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("DataAcessLayer.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId")
                        .IsUnique();

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("DataAcessLayer.Models.Madplan", b =>
                {
                    b.HasOne("DataAcessLayer.Models.Recipe", "Fredag")
                        .WithMany()
                        .HasForeignKey("FredagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAcessLayer.Models.Recipe", "Lørdag")
                        .WithMany()
                        .HasForeignKey("LørdagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAcessLayer.Models.Recipe", "Mandag")
                        .WithMany()
                        .HasForeignKey("MandagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAcessLayer.Models.Recipe", "Onsdag")
                        .WithMany()
                        .HasForeignKey("OnsdagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAcessLayer.Models.Recipe", "Søndag")
                        .WithMany()
                        .HasForeignKey("SøndagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAcessLayer.Models.Recipe", "Tisdag")
                        .WithMany()
                        .HasForeignKey("TisdagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAcessLayer.Models.Recipe", "Torsdag")
                        .WithMany()
                        .HasForeignKey("TorsdagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fredag");

                    b.Navigation("Lørdag");

                    b.Navigation("Mandag");

                    b.Navigation("Onsdag");

                    b.Navigation("Søndag");

                    b.Navigation("Tisdag");

                    b.Navigation("Torsdag");
                });

            modelBuilder.Entity("DataAcessLayer.Models.RecipeIngredient", b =>
                {
                    b.HasOne("DataAcessLayer.Models.Ingredient", "Ingredient")
                        .WithOne("RecipeIngredient")
                        .HasForeignKey("DataAcessLayer.Models.RecipeIngredient", "IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAcessLayer.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("DataAcessLayer.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredient")
                        .IsRequired();
                });

            modelBuilder.Entity("DataAcessLayer.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
